//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Package2Go5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public Currencies()
        {
            this.Items = new HashSet<Items>();
            this.UserProfile = new HashSet<UserProfile>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public decimal currency_rate { get; set; }
    
        public virtual ICollection<Items> Items { get; set; }
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}
