//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Package2Go5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.ItemsRoutes = new HashSet<ItemsRoutes>();
            this.Offers = new HashSet<Offers>();
            this.UsersItems = new HashSet<UsersItems>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string delivery_address { get; set; }
        public string size { get; set; }
        public int delivery_price { get; set; }
        public string note { get; set; }
        public int currency_id { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual ICollection<ItemsRoutes> ItemsRoutes { get; set; }
        public virtual ICollection<Offers> Offers { get; set; }
        public virtual ICollection<UsersItems> UsersItems { get; set; }
    }
}
