//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Package2Go5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public Messages()
        {
            this.UsersMessages = new HashSet<UsersMessages>();
        }
    
        public int id { get; set; }
        public int from { get; set; }
        public int to { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public int statusId { get; set; }
    
        public virtual MessagesStatus MessagesStatus { get; set; }
        public virtual ICollection<UsersMessages> UsersMessages { get; set; }
    }
}
