//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Package2Go5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public Routes()
        {
            this.ItemsRoutes = new HashSet<ItemsRoutes>();
            this.Offers = new HashSet<Offers>();
            this.UsersRoutes = new HashSet<UsersRoutes>();
        }
    
        public int id { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public System.DateTime departure_time { get; set; }
        public System.DateTime delivery_time { get; set; }
        public int status_id { get; set; }
        public string waypoints { get; set; }
    
        public virtual ICollection<ItemsRoutes> ItemsRoutes { get; set; }
        public virtual ICollection<Offers> Offers { get; set; }
        public virtual RouteStatus RouteStatus { get; set; }
        public virtual ICollection<UsersRoutes> UsersRoutes { get; set; }
    }
}
