//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Package2Go5
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_messages
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string message { get; set; }
        public string status { get; set; }
    }
}
