//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Package2Go5
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_routes
    {
        public int id { get; set; }
        public string from { get; set; }
        public string waypoints { get; set; }
        public System.DateTime departure_time { get; set; }
        public System.DateTime delivery_time { get; set; }
        public string status { get; set; }
        public string Username { get; set; }
        public Nullable<int> rate { get; set; }
        public int user_id { get; set; }
    }
}
